controller_list:
  - name: fake_heal_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
initial:  # Define initial robot poses per group
#  - group: heal_arm
#    pose: home

  []